### ISSUE TITLE
Publish latest code to npm

### ISSUE THREAD

**Issue by billiegoose** [noffle/hypergit#15]
The version currently on npm does not export an `index.js` so I can't use it in [`hypergit-service`](https://github.com/wmhilton/hypergit-service).

But do fix #14 first before publishing. 😁

**Comment by ralphtheninja** [comment]
@noffle Mind adding a few more to npm? E.g. @wmhilton, @staltz and myself.

**Comment by billiegoose** [comment]
I myself recommend using Travis do to the publishing using semantic-release.

**Comment by hackergrrl** [comment]
Added @ralphtheninja @wmhilton @staltz! So much awesome effort!
